In [3]:
## Connect to the Database

import pandas as pd
import sqlite3

# 1. Connect to the database file
conn = sqlite3.connect(r"C:/Users/Olaoluwa/Documents/PORA/Data Science/Chinook_Sqlite.sqlite")

In [4]:
tables = pd.read_sql("SELECT name FROM sqlite_master WHERE type='table';", conn)
tables

             name
0           Album
1          Artist
2        Customer
3        Employee
4           Genre
5         Invoice
6     InvoiceLine
7       MediaType
8        Playlist
9   PlaylistTrack
10          Track

In [5]:
# 2. Read a table

df = pd.read_sql("SELECT * FROM Album", conn)
df.head()

   AlbumId                                  Title  ArtistId
0        1  For Those About To Rock We Salute You         1
1        2                      Balls to the Wall         2
2        3                      Restless and Wild         2
3        4                      Let There Be Rock         1
4        5                               Big Ones         3

In [6]:
# 2. Read a table

df = pd.read_sql("SELECT * FROM Artist", conn)
df.head()

   ArtistId               Name
0         1              AC/DC
1         2             Accept
2         3          Aerosmith
3         4  Alanis Morissette
4         5    Alice In Chains

In [7]:
# using a function to load the tables in the db

def load_table(table_name: str) -> pd.DataFrame:
    """
    Load any table from the SQLite database into a pandas DataFrame.
    
    Parameters:
        table_name (str): Name of the table to load.
    
    Returns:
        pd.DataFrame: The table data as a DataFrame.
    """
    query = f"SELECT * FROM {table_name}"  # This creates a SQL query using an f-string.
    df = pd.read_sql_query(query, conn)    # This line executes the SQL query using the database connection.
    return df

In [15]:
Album = load_table("Album")
Artist = load_table("Artist")
Customer = load_table("Customer")
Employee = load_table("Employee")
Genre = load_table("Genre")
Invoice = load_table("Invoice")
InvoiceLine = load_table("InvoiceLine")
MediaType = load_table("MediaType")
Playlist = load_table("Playlist")
PlaylistTrack = load_table("PlaylistTrack")
Track = load_table("Track")

In [11]:
# for index, row in tables.iterrows():
#     table_name = row['name']
#     df_table_name = f"df_{tableName}"
#     df = load_table(table_name)
#     df_table_name = df_table_name
#     print(f"Stored {table_name} table in dataframe df_{tableName}")

   AlbumId                                  Title  ArtistId
0        1  For Those About To Rock We Salute You         1
1        2                      Balls to the Wall         2
2        3                      Restless and Wild         2
3        4                      Let There Be Rock         1
4        5                               Big Ones         3

In [16]:
Artist.head(2)

   ArtistId    Name
0         1   AC/DC
1         2  Accept

In [17]:
Album.head(2)

   AlbumId                                  Title  ArtistId
0        1  For Those About To Rock We Salute You         1
1        2                      Balls to the Wall         2

In [18]:
# joining tables in pandas: df.merge

Artist_Album = Artist.merge(right = Album,
            how = 'outer',
            on = 'ArtistId')

In [19]:
Artist_Album.head(2)

   ArtistId   Name  AlbumId                                  Title
0         1  AC/DC      1.0  For Those About To Rock We Salute You
1         1  AC/DC      4.0                      Let There Be Rock

In [21]:
len(Artist_Album)

418

In [22]:
len(Artist)

275

In [23]:
len(Album)

347

In [ ]:
# join tables employee -> customer -> invoice -> invoiceline

In [ ]:
dataframe = load_table('album')
dataframe.head()